### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by weltonwe** [wvelludo/whmcs-buypage-cielo#1]
onde vai a api neste modulo

**Comment by wvelludo** [comment]
Este módulo faz as requisições na Cielo e encaminha o cliente para pagamento via BuyPage, após finalizado retorna para o whmcs que faz a captura, é só você mandar o módulo para seu whmcs, ativar e configurar via painel. Você não precisa dos arquivos disponibilizados pela cielo no kit de integração para usar o modulo.

**Comment by weltonwe** [comment]
E apos selecionar o cartão ele faze um redirecionamento e volta para a fatura, não aparece pagina de coloca dados do cartão não redireciona para o site da cielo

**Comment by wvelludo** [comment]
Você configurou o módulo informando o código do estabelecimento e chave de acesso? Mesmo como a opção "Ambiente de Testes" ativada deve-se informar o código do ambiente de testes da cielo. Só retorna para a fatura caso não tenha conseguido gerar a transação no ambiente da cielo.
