### ISSUE TITLE
Esse modulo possui Opção de Débito Automático?

### ISSUE THREAD

**Issue by henriquelucas** [wvelludo/whmcs-buypage-cielo#2]
Tem opção de pagamento automático? tenho alguns clientes que esquecem de pagar suas faturas, ou tem preguiça de todo mês de realizar o pagamento e gostariam de pagar via debito automatizo.

**Comment by wvelludo** [comment]
Henrique, ele não faz o debito automático, este tipo de recurso é meio problematico dentro do whmcs já que ele não tem suporte nativo e precisa de algumas estruturas mais complexas para esse tipo de operação, a longo prazo acabam rolando algumas inconsistências.
